# Generated by Django 5.0 on 2024-06-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoisesalaries',
            name='invoise_id',
        ),
    ]
