# Generated by Django 5.0.6 on 2024-06-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedcash',
            name='push_to',
            field=models.CharField(choices=[('الفواتير', 'الفواتير'), ('الاضافات', 'الاضافات')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
