# Generated by Django 5.0 on 2024-06-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_invoisesalaries_invoise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoisesalaries',
            name='invoise_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoisesalaries',
            name='invoise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoise'),
        ),
    ]
