# Generated by Django 5.0.6 on 2024-06-19 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receivedcash_push_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoisesalaries',
            name='invoise_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.invoise'),
            preserve_default=False,
        ),
    ]
