# Generated by Django 5.0.6 on 2024-06-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_salaries_uv_sal_alter_salaries_c_sal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='c_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='faddi_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='film_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='kohley_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='m_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='sapgha_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='slofan_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='special_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='taksir_full_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='taksir_half_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='taksir_rega_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='warnish_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='y_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='zahabi_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='zenk_sal',
            field=models.FloatField(),
        ),
    ]
