# Generated by Django 5.0.6 on 2024-06-24 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_salaries_c_sal_alter_salaries_faddi_sal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='receivedCash',
            field=models.FloatField(verbose_name='النقديه المتبقيه'),
        ),
        migrations.AlterField(
            model_name='client',
            name='totalCash',
            field=models.FloatField(verbose_name='اجمالي النقديه'),
        ),
        migrations.AlterField(
            model_name='invoise',
            name='remaining_cash',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoise',
            name='total_cash',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='receivedcash',
            name='received_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='UV_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='c_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='faddi_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='film_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='k_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='kohley_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='m_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='sapgha_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='slofan_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='special_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='taksir_full_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='taksir_half_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='taksir_rega_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='warnish_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='y_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='zahabi_sal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='zenk_sal',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=15),
        ),
    ]
