# Generated by Django 5.0.6 on 2024-06-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_additional_total_alter_client_receivedcash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoise',
            name='remaining_cash',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoise',
            name='total_cash',
            field=models.FloatField(blank=True),
        ),
    ]
