# Generated by Django 5.0.6 on 2024-06-24 18:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_invoise_remaining_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoise',
            name='remaining_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
