# Generated by Django 5.0.6 on 2024-06-24 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_invoise_remaining_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='total',
            field=models.CharField(max_length=50, verbose_name='الاجمالي'),
        ),
        migrations.AlterField(
            model_name='client',
            name='receivedCash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='النقديه المتبقيه'),
        ),
        migrations.AlterField(
            model_name='client',
            name='totalCash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='اجمالي النقديه'),
        ),
        migrations.AlterField(
            model_name='invoise',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='receivedcash',
            name='received_value',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
    ]
