# Generated by Django 5.0.6 on 2024-06-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_additional_total_alter_client_receivedcash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoisesalaries',
            name='invoise_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoisesalaries',
            name='invoise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoise'),
        ),
    ]
